# Generated by Django 4.1.7 on 2023-03-05 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='категория')),
                ('url', models.SlugField(max_length=160)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='пол')),
                ('url', models.SlugField(max_length=160)),
            ],
            options={
                'verbose_name': 'пол',
                'verbose_name_plural': 'пол',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='products/', verbose_name='фото')),
                ('type', models.CharField(max_length=100, verbose_name='тип')),
                ('color', models.CharField(max_length=100, verbose_name='цвет')),
                ('price', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='цена')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('url', models.SlugField(max_length=160)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='категория')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.gender', verbose_name='пол')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=50, verbose_name='размер товара')),
                ('amount_size', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='количество товара данного размера')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'размер',
                'verbose_name_plural': 'размеры',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to='products.product', verbose_name='товар')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to='products.sizes', verbose_name='размер')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзины пользователей',
            },
        ),
    ]
