# Generated by Django 4.1.7 on 2023-03-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_cart_size_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default=1, max_length=50, verbose_name='размер товара'),
            preserve_default=False,
        ),
    ]
