# Generated by Django 4.1.7 on 2023-03-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_cart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(default=1, max_length=50, verbose_name='размер для корзины'),
            preserve_default=False,
        ),
    ]
