# Generated by Django 4.1.7 on 2023-03-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='photo',
            field=models.ImageField(null=True, upload_to='products/', verbose_name='фото'),
        ),
    ]
