# Generated by Django 4.1.7 on 2023-03-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cart_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='photo',
        ),
    ]
