# Generated by Django 4.1.7 on 2023-03-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_cart_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=20, verbose_name='Id Корзины'),
            preserve_default=False,
        ),
    ]
