# Generated by Django 4.1.7 on 2023-03-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_cart_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_id',
            new_name='cart_number',
        ),
    ]
