# Generated by Django 4.1.7 on 2023-03-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_cart_id_cart_cart_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_number',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
