# Generated by Django 4.1.7 on 2023-03-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_cart_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=20),
        ),
    ]
