# Generated by Django 4.1.7 on 2023-03-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_number',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True),
        ),
    ]
