# Generated by Django 4.1.7 on 2023-03-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_cart_cart_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sum_price',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=20),
        ),
    ]
