# Generated by Django 4.1.7 on 2023-03-19 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_cart_sum_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sum_price',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('size', models.CharField(max_length=50, verbose_name='размер для заказа')),
                ('amount', models.DecimalField(decimal_places=0, default=1, max_digits=20)),
                ('price', models.DecimalField(decimal_places=0, default=1, max_digits=20)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='products.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзины пользователей',
            },
        ),
    ]
