# Generated by Django 4.1.7 on 2023-03-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_cart_sum_price_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='url',
            field=models.SlugField(default=1, max_length=160),
            preserve_default=False,
        ),
    ]
