# Generated by Django 4.1.7 on 2023-04-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_paymentorder_options_paymentorder_phone_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentorder',
            name='order',
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='payment_order_number',
            field=models.CharField(default=1, max_length=50, verbose_name='номер заказа для оплаты'),
            preserve_default=False,
        ),
    ]
