# Generated by Django 4.1.7 on 2023-04-01 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_paymentorder_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_order', to='products.order', verbose_name='заказ'),
        ),
    ]
